source 'https://rubygems.org'

gem 'rake', '~> 10.4.2', '< 11.0'
    # per https://stackoverflow.com/a/35893625/2877364 by
    # https://stackoverflow.com/users/22237/kris
gem 'rspec', '~> 3.4.0'
gem 'vimrunner', '~> 0.3.1'
